export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTH_TOKEN_EXPIRATION_CHECK = 'AUTH_TOKEN_EXPIRATION_CHECK';
export const AUTH_TOKEN_EXPIRATION_CHECK_SUCCESS = 'AUTH_TOKEN_EXPIRATION_CHECK_SUCCESS';
export const AUTH_TOKEN_EXPIRATION_CHECK_FAILURE = 'AUTH_TOKEN_EXPIRATION_CHECK_FAILURE';