# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d21693350a89297fee0d134aafceb3da55f6add7167955e1d76041f411caf9ff34d635a57b227c7fe6cba90fee9cab99fee3c097b6e14bb89e5b61650b3c72c

test:
  secret_key_base: 17a69a3b49df2063d6893aa2434ff439b60e06a55ab4d951499b41d1d7f8e7f3c467fd0ed979417181f3131ee56c008b0278ec550bdc9b719367a3d20ed4d702

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
