source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', 					          '~> 5.1.1'
gem 'mysql2', 					        '~> 0.4.6'
gem 'puma', 					          '~> 3.8', '>= 3.8.2'
gem 'active_model_serializers', '~> 0.10.6'
gem 'sunspot_rails',            '~> 2.2', '>= 2.2.7'
gem 'bcrypt', 					        '~> 3.1', '>= 3.1.11'
gem 'jwt', 						          '~> 2.0.0.beta1'
gem 'rack-cors', 				        '~> 0.4.1'
gem 'sidekiq',                  '~> 5.0'
gem 'tzinfo-data', 				      '~> 1.2017', '>= 1.2017.2', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'groupdate',                '~> 3.2'
gem 'kaminari',                 '~> 1.0', '>= 1.0.1'
gem 'api-pagination',           '~> 4.6', '>= 4.6.3'
# gem 'delayed_job',              '~> 4.1', '>= 4.1.2'

group :development, :test do
  gem 'byebug', 				        '~> 9.0', '>= 9.0.6',       platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'hirb',                   '~> 0.7.3'
  gem 'hirb-unicode',           '~> 0.0.5'
  gem 'listen',                 '>= 3.0.5', '< 3.2'
  gem 'sunspot_solr',           '~> 2.2', '>= 2.2.7'
  # gem 'rails-erd',              '~> 1.5', '>= 1.5.2'
  gem 'railroady',              '~> 1.5', '>= 1.5.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen',  '~> 2.0.0'
end
